version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: widen
    labels:
      - npm
      - dependencies
      - automerge
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
