name: Repo Setup

on: [push]

jobs:
  setup:
    name: Setup repo configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set labels
        uses: actions/github-script@master
        continue-on-error: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var labels = [
              {name: 'dada', color: 'CCCCCC'},
              {name: 'damdam', color: 'CCCCCC'},
              {name: 'dede', color: 'CCCCCC'},
              {name: 'doudou', color: 'CCCCCC'},
            ]

            return Promise.all(
              labels.map(label => 
                github.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                }).catch((e) => {
                  github.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color
                  })
                })
              )
            )

      - name: Remove repo setup file
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          remove: '.github/workflows/repo-setup.yml'
          message: 'Remove repo setup file'
