name: Repo Setup

on: [push]

jobs:
  setup:
    name: Setup repo configuration
    runs-on: ubuntu-latest
    steps:
      - name: Set labels
        uses: actions/github-script@master
        continue-on-error: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var labels = [
              {name: 'dada', color: 'CCCCCC'},
              {name: 'damdam', color: 'CCCCCC'},
              {name: 'dede', color: 'CCCCCC'},
              {name: 'doudou', color: 'CCCCCC'},
            ]
            
            return Promise.all(
              labels.map(label => 
                github.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                }).catch((e) => {
                  github.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color
                  })
                })
              )
            )

      # - name: Delete this setup file
      #   uses: actions/github-script@master
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       return github.repos.getContent({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         path: '.github/workflows/repo-setup.yml',
      #       }).then((res) => {
      #         github.repos.deleteFile({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           path: '.github/workflows/repo-setup.yml',
      #           message: 'Delete repository setup file',
      #           sha: res.data.sha,
      #         })
      #       })
