name: Repo Setup

on: push

jobs:
  setup:
    name: Setup repo configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set labels
        uses: actions/github-script@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var labels = [
              {name: 'wip', color: '00cc99', description: 'Work in progress'},
              {name: 'high-priority', color: 'ff9933', description: 'High priority'},
              {name: 'medium-priority', color: 'ff9999', description: 'Medium priority'},
              {name: 'low-priority', color: 'ff99ff', description: 'Low priority'},
            ]

            var {owner, repo} = context.repo
            return Promise.all(
              labels.map(({name, color, description}) => 
                github.issues.getLabel({owner, repo, name})
                .catch((e) => 
                  github.issues.createLabel({ owner, repo, name, color, description })
                )
              )
            )
      # - name: Set topics
      #   uses: actions/github-script@master
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       var topics = ['npm', 'library', 'es6', 'cjs', 'iife']
      #       var {owner, repo} = context.repo
      #       return github.repos.getAllTopics({
      #         owner,
      #         repo,
      #       }).then((res) =>
      #         github.repos.replaceAllTopics({
      #           owner,
      #           repo,
      #           names: [...res.data.names, ...topics]
      #         })
      #       )
      # - name: Remove repo setup file
      #   uses: EndBug/add-and-commit@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     remove: '.github/workflows/repo-setup.yml'
      #     message: 'Remove repo setup file'
