name: Stale issues and pull requests
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    name: Check issues and pull requests
    runs-on: ubuntu-latest
    steps:
    - name: No priority specified
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 1
        days-before-close: 1
        stale-issue-message: This issue had no activity for **2 months**. It will be closed in **one week** unless there is some new activity.
        stale-issue-label: stale
        exempt-issue-labels: high-priority,medium-priority,low-priority
        stale-pr-message: This pull request had no activity for **2 months**. It will be closed in **one week** unless there is some new activity.
        stale-pr-label: stale
        exempt-pr-labels: high-priority,medium-priority,low-priority

    - name: Low-priority
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: low-priority
        days-before-stale: 2
        days-before-close: 2
        stale-issue-message: This issue had no activity for **3 months**. It will be closed in **one week** unless there is some new activity.
        stale-issue-label: stale
        stale-pr-message: This pull request had no activity for **3 months**. It will be closed in **one week** unless there is some new activity.
        stale-pr-label: stale

    - name: Medium-priority
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: medium-priority
        days-before-stale: 3
        days-before-close: 3
        stale-issue-message: This issue had no activity for **3 months**. It will be closed in **two weeks** unless there is some new activity.
        stale-issue-label: stale
        stale-pr-message: This pull request had no activity for **3 months**. It will be closed in **two weeks** unless there is some new activity.
        stale-pr-label: stale

    - name: High-priority
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: high-priority
        days-before-stale: 4
        days-before-close: 4
        stale-issue-message: This issue had no activity for **3 months**. It will be closed in **three weeks** unless there is some new activity.
        stale-issue-label: stale
        stale-pr-message: This pull request had no activity for **3 months**. It will be closed in **three weeks** unless there is some new activity.
        stale-pr-label: stale
